runtime: nodejs10

instance_class: F1

automatic_scaling:
  min_instances: 1

inbound_services:
- warmup

handlers:
  - url: /_ah/warmup
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /api/.*
    secure: always
    script: auto
  - url: /static
    secure: always
    static_dir: client/build/static
  - url: /(.*\.(json|ico|js))$
    secure: always
    static_files: client/build/\1
    upload: client/build/.*\.(json|ico|js)$
  - url: .*
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
