runtime: nodejs10

instance_class: F1

handlers:
  - url: /api/.*
    secure: always
    script: auto
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /
    static_dir: client/build
